#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : tpm2-tools
Version  : 3.1.3
Release  : 1
URL      : https://github.com/tpm2-software/tpm2-tools/releases/download/3.1.3/tpm2-tools-3.1.3.tar.gz
Source0  : https://github.com/tpm2-software/tpm2-tools/releases/download/3.1.3/tpm2-tools-3.1.3.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause
Requires: tpm2-tools-bin = %{version}-%{release}
Requires: tpm2-tools-license = %{version}-%{release}
Requires: tpm2-tools-man = %{version}-%{release}
BuildRequires : pkgconfig(cmocka)
BuildRequires : pkgconfig(libcrypto)
BuildRequires : pkgconfig(libcurl)
BuildRequires : pkgconfig(tss2-mu)
BuildRequires : pkgconfig(tss2-sys)

%description
[![Build Status](https://travis-ci.org/tpm2-software/tpm2-tools.svg?branch=3.X)](https://travis-ci.org/tpm2-software/tpm2-tools)
<a href="https://scan.coverity.com/projects/01org-tpm2-0-tools">
<img alt="Coverity Scan Build Status"
src="https://scan.coverity.com/projects/13105/badge.svg"/>  
</a>
[![Coverage Status](https://coveralls.io/repos/github/01org/tpm2-tools/badge.svg?branch=3.X)](https://coveralls.io/github/01org/tpm2-tools?branch=3.X)

%package bin
Summary: bin components for the tpm2-tools package.
Group: Binaries
Requires: tpm2-tools-license = %{version}-%{release}
Requires: tpm2-tools-man = %{version}-%{release}

%description bin
bin components for the tpm2-tools package.


%package license
Summary: license components for the tpm2-tools package.
Group: Default

%description license
license components for the tpm2-tools package.


%package man
Summary: man components for the tpm2-tools package.
Group: Default

%description man
man components for the tpm2-tools package.


%prep
%setup -q -n tpm2-tools-3.1.3

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1541128193
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1541128193
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/tpm2-tools
cp LICENSE %{buildroot}/usr/share/package-licenses/tpm2-tools/LICENSE
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/tpm2_activatecredential
/usr/bin/tpm2_certify
/usr/bin/tpm2_create
/usr/bin/tpm2_createpolicy
/usr/bin/tpm2_createprimary
/usr/bin/tpm2_dictionarylockout
/usr/bin/tpm2_encryptdecrypt
/usr/bin/tpm2_evictcontrol
/usr/bin/tpm2_getcap
/usr/bin/tpm2_getmanufec
/usr/bin/tpm2_getpubak
/usr/bin/tpm2_getpubek
/usr/bin/tpm2_getrandom
/usr/bin/tpm2_hash
/usr/bin/tpm2_hmac
/usr/bin/tpm2_listpersistent
/usr/bin/tpm2_load
/usr/bin/tpm2_loadexternal
/usr/bin/tpm2_makecredential
/usr/bin/tpm2_nvdefine
/usr/bin/tpm2_nvlist
/usr/bin/tpm2_nvread
/usr/bin/tpm2_nvreadlock
/usr/bin/tpm2_nvrelease
/usr/bin/tpm2_nvwrite
/usr/bin/tpm2_pcrevent
/usr/bin/tpm2_pcrextend
/usr/bin/tpm2_pcrlist
/usr/bin/tpm2_quote
/usr/bin/tpm2_rc_decode
/usr/bin/tpm2_readpublic
/usr/bin/tpm2_rsadecrypt
/usr/bin/tpm2_rsaencrypt
/usr/bin/tpm2_send
/usr/bin/tpm2_sign
/usr/bin/tpm2_startup
/usr/bin/tpm2_takeownership
/usr/bin/tpm2_unseal
/usr/bin/tpm2_verifysignature

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/tpm2-tools/LICENSE

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/tpm2_activatecredential.1
/usr/share/man/man1/tpm2_certify.1
/usr/share/man/man1/tpm2_create.1
/usr/share/man/man1/tpm2_createpolicy.1
/usr/share/man/man1/tpm2_createprimary.1
/usr/share/man/man1/tpm2_dictionarylockout.1
/usr/share/man/man1/tpm2_encryptdecrypt.1
/usr/share/man/man1/tpm2_evictcontrol.1
/usr/share/man/man1/tpm2_getcap.1
/usr/share/man/man1/tpm2_getmanufec.1
/usr/share/man/man1/tpm2_getpubak.1
/usr/share/man/man1/tpm2_getpubek.1
/usr/share/man/man1/tpm2_getrandom.1
/usr/share/man/man1/tpm2_hash.1
/usr/share/man/man1/tpm2_hmac.1
/usr/share/man/man1/tpm2_listpersistent.1
/usr/share/man/man1/tpm2_load.1
/usr/share/man/man1/tpm2_loadexternal.1
/usr/share/man/man1/tpm2_makecredential.1
/usr/share/man/man1/tpm2_nvdefine.1
/usr/share/man/man1/tpm2_nvlist.1
/usr/share/man/man1/tpm2_nvread.1
/usr/share/man/man1/tpm2_nvreadlock.1
/usr/share/man/man1/tpm2_nvrelease.1
/usr/share/man/man1/tpm2_nvwrite.1
/usr/share/man/man1/tpm2_pcrevent.1
/usr/share/man/man1/tpm2_pcrextend.1
/usr/share/man/man1/tpm2_pcrlist.1
/usr/share/man/man1/tpm2_quote.1
/usr/share/man/man1/tpm2_rc_decode.1
/usr/share/man/man1/tpm2_readpublic.1
/usr/share/man/man1/tpm2_rsadecrypt.1
/usr/share/man/man1/tpm2_rsaencrypt.1
/usr/share/man/man1/tpm2_send.1
/usr/share/man/man1/tpm2_sign.1
/usr/share/man/man1/tpm2_startup.1
/usr/share/man/man1/tpm2_takeownership.1
/usr/share/man/man1/tpm2_unseal.1
/usr/share/man/man1/tpm2_verifysignature.1
